config/routes.rb
Rails.application.routes.draw do
  resources :follow_up_surveys

  resources :initial_surveys

  get 'static_pages/home'
  get 'static_pages/admin', :path => "admin"
  get 'static_pages/thank_you', :path => "thank_you"
  
  root 'static_pages#home'

  resources :simulations do
    get 'add_comments'
  end

end

app/models/simulation.rb
class Simulation < ActiveRecord::Base
  before_save :calc_icbm_avail
  before_save :calc_subs_at_sea
  before_save :calc_subs_plus_icbms
  before_save :calc_subs_plus_bombs
  before_save :calc_subs_navy
  before_save :calc_subs_mirv
  before_save :calc_weaps_at_sea
  before_save :calc_red_blue_icbms
  before_save :calc_red_first_strike
  before_save :calc_red_surviving
  before_save :calc_blue_surviving
  before_save :calc_delta_surviving
  before_save :calc_ratio_surviving

  MIRVRATIOS = [[1, 1.0], [2, 2.0], [3, 3.0]]
  TARGETINGRATIOS = [["0:1", 0], ["1:1", 1], ["2:1", 2]]

  def self.to_csv(simulations)
    CSV.generate do |csv|
      csv << column_names
      simulations.each do |simulation|
        csv << simulation.attributes.values
      end
    end
  end

  def calc_icbm_avail
    unless self.icbmMax.blank? || self.icbmProb.blank? || self.icbmMirv.blank?
      self.icbmAvail = (self.icbmMax * self.icbmProb * self.icbmMirv).ceil
    end
  end

  def calc_subs_at_sea
    self.subsRoundUp = true
    unless self.subsOperational.blank? || self.subsSeaRate.blank?
      self.subsAtSea = (self.subsOperational * self.subsSeaRate).floor
    end
  end

  def calc_subs_plus_bombs
    unless self.subsPlusIcbms.blank?
      if self.bombsPercentage.blank?
        self.bombsPercentage = 1
      end
      if self.bombsPostStrike.blank? || self.bombsPostStrike == 0
        self.subsPlusBombs = self.subsPlusIcbms + self.bombsNumber
      else
        self.subsPlusBombs = self.subsPlusIcbms + (self.bombsPostStrike * self.bombsPercentage)
      end
    end
  end

  def calc_subs_plus_icbms
    unless self.subsWeaps.blank? || self.icbmAvail.blank?
      self.subsPlusIcbms = self.subsWeaps + self.icbmAvail
    end
  end

  def calc_subs_navy
    unless self.icbmMax.blank? || self.blueInventory.blank? || self.bombsNumber.blank?
      if self.bombsPostStrike.blank? 
        self.bombsPostStrike = 0
      end
      if self.bombsPercentage.blank?
        self.bombsPercentage = 1
      end
      if self.icbmMirv
        self.subsNavy = self.blueInventory - (self.icbmMax * self.icbmMirv) - (self.bombsPostStrike)
      else
        self.subsNavy = self.blueInventory - self.icbmMax - (self.bombsPostStrike)
      end
    end
  end

  def calc_subs_mirv
    unless self.subsNavy.blank? || self.subsOperational.blank? || self.subsTubes.blank?
      if subsOperational == 0 || subsTubes == 0
        self.subsMirv = 0
      else
        self.subsMirv = (self.subsNavy.to_f / (self.subsOperational.to_f * self.subsTubes.to_f)).round(2)
      end
      if self.subsMirv > 8
        self.subsMirv = 8
      end
    end
  end

  def calc_weaps_at_sea
    unless self.subsMirv.blank? || self.subsTubes.blank? || self.subsAtSea.blank?
      self.subsWeaps = self.subsMirv * self.subsTubes * self.subsAtSea
    end
  end

  def calc_red_blue_icbms
    unless self.icbmMax.blank? || self.redRatio.blank?
      if self.redTarget
        self.redBlueIcbms = (self.icbmMax * self.redRatio) + (self.icbmMax / 10)
      else
        self.redBlueIcbms = self.icbmMax * self.redRatio
      end
    end
  end

  def calc_red_first_strike
    unless self.redBlueIcbms.blank? || self.redBases.blank?
      self.redFirstStrike = self.redBlueIcbms + self.redBases
    end
    #if self.icbmBlueLaunch
      #self.redFirstStrike = self.redInventory - self.redBlueIcbms - self.icbmAvail
    #else
      #self.redFirstStrike = self.redInventory - self.redBlueIcbms
    #end
  end

  def calc_red_surviving
    unless self.redInventory.blank? || self.redFirstStrike.blank?
      self.redSurviving = self.redInventory - self.redFirstStrike
    end
  end

  def calc_blue_surviving
    if self.icbmBlueLaunch
      self.blueSurviving = self.subsAtSea * self.subsTubes * self.subsMirv
    else
      if self.redRatio == 0
        if self.icbmMax
          self.blueSurviving = (self.subsAtSea * self.subsTubes * self.subsMirv) + self.icbmMax
        else
          self.blueSurviving = (self.subsAtSea * self.subsTubes * self.subsMirv)
        end
      else
        if self.redPk == 1
          self.blueSurviving = self.subsAtSea * self.subsTubes * self.subsMirv
        else
          if self.icbmProb
            #self.blueSurviving = (self.subsAtSea * self.subsTubes * self.subsMirv) + (self.icbmMax * (1 - (self.redPk*self.redRatio))) * self.icbmProb
            self.blueSurviving = (self.subsAtSea * self.subsTubes * self.subsMirv) + ((self.icbmMax * self.icbmMirv) * (1 - self.redPk))
          else
            self.blueSurviving = (self.subsAtSea * self.subsTubes * self.subsMirv) + ((self.icbmMax * self.icbmMirv) * (1 - self.redPk))
          end
        end
      end
    end
    if self.bombsSurvive
      if self.bombsPercentage.blank?
        self.bombsPercentage = 1
      end
      if self.bombsPostStrike
        self.blueSurviving += (self.bombsPostStrike * self.bombsPercentage)
      else
        self.blueSurviving += self.bombsNumber
      end
    end
  end

  def calc_delta_surviving
    unless self.redSurviving.blank? || self.blueSurviving.blank?
      self.deltaSurviving = self.blueSurviving - self.redSurviving
    end
  end

  def calc_ratio_surviving
    unless self.redSurviving.blank? || self.blueSurviving.blank?
      self.ratioSurviving = (self.redSurviving.to_f / self.blueSurviving.to_f).round(1)
    end
  end
end

app/controllers/simulations_controller.rb
class SimulationsController < ApplicationController
  before_action :set_simulation, only: [:show, :edit, :update, :destroy]

  # GET /simulations
  # GET /simulations.json
  def index
    @simulations = Simulation.all
    respond_to do |format|
      format.html { render :action => "index" }
      format.csv { send_data Simulation.to_csv(@simulations) }
    end
  end

  # GET /simulations/1
  # GET /simulations/1.json
  def show
  end

  # GET /simulations/new
  def new
    @simulation = Simulation.new
  end

  # GET /simulations/1/edit
  def edit
  end

  def add_comments
    @simulation = Simulation.find(params[:simulation_id])
    @simulation.comments = (params[:comments])
    @simulation.recommendComments = (params[:recommendComments])
    @simulation.unexpectedComments = (params[:unexpectedComments])
    @simulation.vulnerableComments = (params[:vulnerableComments])

    @simulation.save
  end

  # POST /simulations
  # POST /simulations.json
  def create
    @simulation = Simulation.new(simulation_params)
    @simulation.user = cookies[:user] 

    respond_to do |format|
      if @simulation.save
        format.html { redirect_to @simulation, notice: 'Simulation was successfully created.' }
        format.json { render :show, status: :created, location: @simulation }
      else
        format.html { render :new }
        format.json { render json: @simulation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /simulations/1
  # PATCH/PUT /simulations/1.json
  def update
    respond_to do |format|
      if @simulation.update(simulation_params)
        if @simulation.comments
          if cookies[:doneForceStructure]
            format.html { redirect_to new_follow_up_survey_path, notice: 'Comments were successfully added.' }
            format.json { render :show, status: :ok, location: @simulation }
          else
            format.html { redirect_to new_simulation_path, notice: 'Comments were successfully added.' }
            format.json { render :show, status: :ok, location: @simulation }
          end
        else
          format.html { redirect_to @simulation, notice: 'Simulation was successfully updated.' }
          format.json { render :show, status: :ok, location: @simulation }
        end
      else
        format.html { render :edit }
        format.json { render json: @simulation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /simulations/1
  # DELETE /simulations/1.json
  def destroy
    @simulation.destroy
    respond_to do |format|
      format.html { redirect_to simulations_url, notice: 'Simulation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_simulation
      @simulation = Simulation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def simulation_params
      params.require(:simulation).permit(
        :blueInventory, 
        :redInventory, 
        :icbmMax, 
        :icbmMirv, 
        :icbmProb, 
        :icbmAvail, 
        :icbmBlueLaunch, 
        :icbmBluePk, 
        :subsOperational, 
        :subsAtSea, 
        :subsRoundUp, 
        :subsWeaps, 
        :subsPlusIcbms, 
        :subsPlusBombs, 
        :subsTubes, 
        :subsMirv, 
        :subsNavy, 
        :bombsNumber, 
        :bombsSurvive, 
        :bombsPostStrike, 
        :bombsPercentage,
        :redRatio, 
        :redTarget, 
        :redPk,
        :redBases, 
        :redBlueIcbms, 
        :redFirstStrike, 
        :redSurviving, 
        :blueSurviving, 
        :deltaSurviving, 
        :ratioSurviving, 
        :subsSeaRate, 
        :user, 
        :recommendComments,
        :unexpectedComments,
        :vulnerableComments,
        :comments
      )
    end
end

app/helpers/simulations_helper.rb
module SimulationsHelper
end

app/views/simulations/add_comments.html.erb
<header>
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <h1><i class="fa fa-bomb"></i>1st Strike Advantage Calculator (Add Comments)</h1>
      </div>
    </div>
  </div>
</header>
<div class="container">
  <%= form_for(@simulation) do |f| %>
  <% if @simulation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@simulation.errors.count, "error") %> prohibited this initial_survey from being saved:</h2>

      <ul>
      <% @simulation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="form-group col-sm-12">
      <%= f.label :recommendComments, "Why do you recommend this arsenal strategy?", :class => "control-label user-label" %>
      <%= f.text_area :recommendComments, :class => "form-control", :required => true, :rows => 6 %>
    </div>
    <div class="form-group col-sm-12">
      <%= f.label :unexpectedComments, "Did your analysis uncover anything unexpected or surprising?", :class => "control-label user-label" %>
      <%= f.text_area :unexpectedComments, :class => "form-control", :required => true, :rows => 6 %>
    </div>
    <div class="form-group col-sm-12">
      <%= f.label :vulnerableComments, "Did you find any combinations an adversary might consider especially vulnerable?", :class => "control-label user-label" %>
      <%= f.text_area :vulnerableComments, :class => "form-control", :required => true, :rows => 6 %>
    </div>
    <div class="form-group col-sm-12">
      <%= f.label :comments, "Do you have any additional comments?", :class => "control-label user-label" %>
      <%= f.text_area :comments, :class => "form-control", :required => true, :rows => 10 %>
    </div>
    <div class="form-group col-sm-12">
      <%= f.submit "Save and proceed to next analysis", :class => "btn btn-primary" %><br><br>
      <%= f.submit "Save and finish with force structure analysis", :class => "btn btn-primary done" %>
    </div>
    <% end %>
  </div>
</div>
<script>
  function createCookie(name,value,days) {
      if (days) {
          var date = new Date();
          date.setTime(date.getTime()+(days*24*60*60*1000));
          var expires = "; expires="+date.toGMTString();
      }
      else var expires = "";
      document.cookie = name+"="+value+expires+"; path=/";
  }
  $('.done').click(function() {
    createCookie('doneForceStructure','true');
  })
</script>

app/views/simulations/edit.html.erb
<header>
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <h1><i class="fa fa-bomb"></i>1st Strike Advantage Calculator (Edit Simulation)</h1>
      </div>
    </div>
  </div>
</header>
<div class="container">
  <%= render 'form' %>
</div>
<%= render "helper_text" %>

app/views/simulations/index.html.erb
<h1>Listing simulations</h1>

<table>
  <thead>
    <tr>
      <th>Blueinventory</th>
      <th>Redinventory</th>
      <th>Icbmmax</th>
      <th>Icbmmirv</th>
      <th>Icbmprob</th>
      <th>Icbmavail</th>
      <th>Icbmbluelaunch</th>
      <th>Icbmbluepk</th>
      <th>Subsoperational</th>
      <th>Subsatsea</th>
      <th>Subsroundup</th>
      <th>Subsweaps</th>
      <th>Subsplusicbms</th>
      <th>Subsplusbombs</th>
      <th>Substubes</th>
      <th>Subsmirv</th>
      <th>Subsnavy</th>
      <th>Bombsnumber</th>
      <th>Bombssurvive</th>
      <th>Bombspoststrike</th>
      <th>Redratio</th>
      <th>Redtarget</th>
      <th>Redpk</th>
      <th>Redbases</th>
      <th>Redblueicbms</th>
      <th>Redfirststrike</th>
      <th>Redsurviving</th>
      <th>Bluesurviving</th>
      <th>Deltasurviving</th>
      <th>Ratiosurviving</th>
      <th>User</th>
      <th>Comments</th>
      <th>Recommend Comments</th>
      <th>Vulnerable Comments</th>
      <th>Unexpected Comments</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @simulations.each do |simulation| %>
      <tr>
        <td><%= simulation.blueInventory %></td>
        <td><%= simulation.redInventory %></td>
        <td><%= simulation.icbmMax %></td>
        <td><%= simulation.icbmMirv %></td>
        <td><%= simulation.icbmProb %></td>
        <td><%= simulation.icbmAvail %></td>
        <td><%= simulation.icbmBlueLaunch %></td>
        <td><%= simulation.icbmBluePk %></td>
        <td><%= simulation.subsOperational %></td>
        <td><%= simulation.subsAtSea %></td>
        <td><%= simulation.subsRoundUp %></td>
        <td><%= simulation.subsWeaps %></td>
        <td><%= simulation.subsPlusIcbms %></td>
        <td><%= simulation.subsPlusBombs %></td>
        <td><%= simulation.subsTubes %></td>
        <td><%= simulation.subsMirv %></td>
        <td><%= simulation.subsNavy %></td>
        <td><%= simulation.bombsNumber %></td>
        <td><%= simulation.bombsSurvive %></td>
        <td><%= simulation.bombsPostStrike %></td>
        <td><%= simulation.redRatio %></td>
        <td><%= simulation.redTarget %></td>
        <td><%= simulation.redPk %></td>
        <td><%= simulation.redBases %></td>
        <td><%= simulation.redBlueIcbms %></td>
        <td><%= simulation.redFirstStrike %></td>
        <td><%= simulation.redSurviving %></td>
        <td><%= simulation.blueSurviving %></td>
        <td><%= simulation.deltaSurviving %></td>
        <td><%= simulation.ratioSurviving %></td>
        <td><%= simulation.user %></td>
        <td><%= simulation.comments %></td>
        <td><%= simulation.recommendComments %></td>
        <td><%= simulation.vulnerableComments %></td>
        <td><%= simulation.unexpectedComments %></td>
        <td><%= link_to 'Show', simulation %></td>
        <td><%= link_to 'Edit', edit_simulation_path(simulation) %></td>
        <td><%= link_to 'Destroy', simulation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Simulation', new_simulation_path %>

app/views/simulations/new.html.erb
<header>
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <h1><i class="fa fa-bomb"></i>1st Strike Advantage Calculator (New Simulation)</h1>
      </div>
    </div>
  </div>
</header>
<div class="container">
  <%= render 'form' %>
</div>
<%= render "helper_text" %>

app/views/simulations/show.html.erb
<header>
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <h1><i class="fa fa-bomb"></i>1st Strike Advantage Calculator (Simulation Results)</h1>
      </div>
    </div>
  </div>
</header>
<div class="container">
  <p id="notice"><%= notice %></p>
  <div class="row">
    <div class="form-fields-module module-top">
      <h2>Your <em>Arsenal Strategy</em> following attack</h2>
      <div class="form-group col-md-6 col-lg-3">
        Defender warheads remaining<br>
        <strong><%= @simulation.blueSurviving %></strong>
      </div>
      <div class="form-group col-md-6 col-lg-3">
        Attacker warheads remaining<br>
        <strong><%= @simulation.redSurviving %></strong>
      </div>
      <div class="form-group col-md-6 col-lg-3">
        Defender advantage<br>
        <strong><%= @simulation.deltaSurviving %></strong>
      </div>
      <div class="form-group col-md-6 col-lg-3">
        Ratio Defender:Attacker<br>
        <strong>1:<% if @simulation.ratioSurviving == Float::INFINITY %>0<% else %><%= @simulation.ratioSurviving %><% end %></strong>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-fields-module">
        <h2>Defender surviving warheads</h2>
        <div class="form-group">
          ICBM Surviving<br>
          <strong>
            <% if @simulation.redPk == 0 %>
              <%= sprintf('%g', (@simulation.icbmMax * @simulation.icbmMirv)) %>
              <!-- 90 should be 10 -->
            <% else %>
              <%=  sprintf('%g', (@simulation.icbmMax * @simulation.icbmMirv * (1 - @simulation.redPk))) %>
            <% end %>
          </strong>
        </div>
        <div class="form-group">
          Warheads surviving on bombers<br>
          <strong><%= sprintf('%g', (@simulation.bombsPostStrike * @simulation.bombsPercentage)) %></strong>
        </div>
        <div class="form-group">
          SSBN<br>
          <strong><%= sprintf('%g', (@simulation.subsNavy * @simulation.subsSeaRate)) %></strong>
        </div>
        <!--<div class="form-group">
          SLBM MIRV ratio<br>
          <strong><%#= @simulation.subsMirv %></strong>
        </div>-->
        
      </div>
      <br><br>
    </div>
    <div class="col-md-6">
      <div class="form-fields-module">
        <h2>Attacker warheads used in First Strike</h2>
        <div class="form-group">
          Attacker weapons targeted on Defender ICBMs<br>
          <strong><%= @simulation.redBlueIcbms %></strong>
        </div>
        <div class="form-group">
          Total Attacker weapons assigned first strike<br>
          <strong><%= @simulation.redFirstStrike %></strong>
        </div>
      </div>
    </div>
    
  </div>
    <!--<div class="form-fields-module module-top">
      <div class="form-group">
          Defender bombers<br>
          <strong><%#= @simulation.subsPlusBombs %></strong>
        </div>
      </div>-->
      <h1>Assessed Inputs</h1>
    <div class="form-fields-module module-top row">
      <h2>Total Warheads</h2>
      <div class="form-group col-md-6">
        Defender force<br>
        <strong><%= @simulation.blueInventory %></strong>
      </div>
      <div class="form-group col-md-6">
        Attacker force<br>
        <strong><%= @simulation.redInventory %></strong>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-fields-module">
        <h2>Defender force ICBMs</h2>
        <div class="form-group">
          Number of ICBMs<br>
          <strong><%= @simulation.icbmMax %></strong>
        </div>
        <div class="form-group">
          MIRV ratio on ICBMs<br>
          <strong><%= @simulation.icbmMirv %></strong>
        </div>
        <div class="form-group">
          Defender launch under attack<br>
          <strong>
            <% if @simulation.icbmBlueLaunch %>yes<% end %>
            <% if !@simulation.icbmBlueLaunch %>no<% end %>
          </strong>
        </div>
        <div class="form-group">
          Probability of ICBM launch prior to Attacker first strike<br>
          <strong><%#= @simulation.icbmProb %></strong>
        </div>
        <div class="form-group">
          Defender P<sub>k</sub> against Attacker<br>
          <strong><%#= @simulation.icbmBluePk %></strong>
        </div>
      </div>
      <div class="form-fields-module">
        <h2>Defender Force Bombers</h2>
        <div class="form-group">
          Number of bombers<br>
          <strong><%= @simulation.bombsNumber %></strong>
        </div>
        <div class="form-group">
          Bombers generated and survive<br>
          <strong>
            <% if @simulation.bombsSurvive %>yes<% end %>
            <% if !@simulation.bombsSurvive %>no<% end %>
          </strong>
        </div>
        <div class="form-group">
          Additional weapons loaded on bombers<br>
          <strong><%= @simulation.bombsPostStrike %></strong>
        </div>
        <div class="form-group">
          Rate of Defender bombers that are generated and survive attack<br>
          <strong><%= @simulation.bombsPercentage %></strong>
        </div>
      </div>
      <div class="form-fields-module">
        <h2>Defender force SSBN</h2>
        <div class="form-group">
          Number of operational Defender subs<br>
          <strong><%= @simulation.subsOperational %></strong>
        </div>
        <div class="form-group">
          "At sea rate" for Defender subs<br>
          <strong><%= @simulation.subsSeaRate %></strong>
        </div>
        <div class="form-group">
          Number of tubes per sub<br>
          <strong><%= @simulation.subsTubes %></strong>
        </div>
        <div class="form-group">
          Number of weapons assigned to navy<br>
          <strong><%= @simulation.subsNavy %></strong>
        </div>
      </div>
    </div><!--/.col-md-6-->
    <div class="col-md-6">
      <div class="form-fields-module">
        <h2>Attacker force</h2>
        <div class="form-group">
          Attacker targeting ratio on Defender ICBMs<br>
          <strong><%= @simulation.redRatio %></strong>
        </div>
        <div class="form-group">
          Attacker target Defender LCCs<br>
          <strong>
            <% if @simulation.redTarget %>yes<% end %>
            <% if !@simulation.redTarget %>no<% end %>
          </strong>
        </div>
        <div class="form-group">
          Attacker P<sub>k</sub> against Defender ICBMs<br>
          <strong><%= @simulation.redPk %></strong>
        </div>
        <div class="form-group">
          Attacker weapons targeted on bases and crit assets<br>
          <strong><%= @simulation.redBases %></strong>
        </div>
      </div>
      <div class="option-buttons">
        <p><%= link_to 'Edit force structure', edit_simulation_path(@simulation), :class => "btn btn-primary" %></p>
        <p><%= link_to 'Recommend this force structure', simulation_add_comments_path(@simulation), :class => "btn btn-primary" %></p>
      </div>
      <!--<div class="form-fields-module results-module">
        <h2>Results of your choices</h2>-->
        <!--<div class="form-group">
          ICBMs available prior to attacker first strike<br>
          <strong><%#= @simulation.icbmAvail %></strong>
        </div>
        <hr> hide per hunter-->
        <!--<div class="form-group">
          Numerical Defender advantage<br>
          <strong><%#= @simulation.deltaSurviving %></strong>
        </div>
        <div class="form-group">
          Ratio Defender:Attacker advantage<br>
          <strong>1:<%#= @simulation.ratioSurviving %></strong>
        </div>-->

        <!--Defender ICBMs successful against attacker-->
        
    
        <!--<div class="form-group">
          Plus ICBMs<br>
          <strong><%#= @simulation.subsPlusIcbms %></strong>
        </div>hide per hunter
        <div class="form-group">
          Additional weapons available on generated bombers (blank if bombers were not generated)<br>
          <strong><%#= @simulation.subsPlusBombs %></strong>
        </div>-->
    
      </div>
    </div><!--/.col-lg-6-->
  </div>
</div>