config/routes.rb
Rails.application.routes.draw do
  resources :follow_up_surveys

  resources :initial_surveys

  get 'static_pages/home'
  get 'static_pages/admin', :path => "admin"
  get 'static_pages/thank_you', :path => "thank_you"
  
  root 'static_pages#home'

  resources :simulations do
    get 'add_comments'
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/admin.html.erb
<div class="row">
  <div class="col-sm-12 col-md-6 col-md-push-3">
    <h1>Administration area</h1>
    <h2>Simulations data</h2>
    <ul>
      <li><%= link_to 'View in browser', simulations_path %></li>
      <li><%= link_to 'Download CSV', 'simulations.csv' %></li>
    </ul>
    <h2>Initial surveys data</h2>
    <ul>
      <li><%= link_to 'View in browser', initial_surveys_path %></li>
      <li><%= link_to 'Download CSV', 'initial_surveys.csv' %></li>
    </ul>
    <h2>Follow up surveys data</h2>
    <ul>
      <li><%= link_to 'View in browser', follow_up_surveys_path %></li>
      <li><%= link_to 'Download CSV', 'follow_up_surveys.csv' %></li>
    </ul>
  </div>
</div>

app/views/static_pages/home.html.erb
<div class="container">
<div class="row">
  <div class="col-sm-12 col-md-6 col-md-push-3">
    <i class="fa fa-bomb fa-hero"></i>
    <h1>Five Nuclear Arsenals</h1>
    <p>To proceed, please confirm that you are 18 or older.</p>

    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
      I am over 18
    </button>

    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            <h4 class="modal-title" id="myModalLabel">Consent form</h4>
          </div>
          <div class="modal-body">
            <p><strong>Northeastern University, Department of: Law and Policy</strong><br>
            <strong>Name of Investigators: Principal Investigator:</strong> Dr Casper Harteveld<br>
            <strong>Student Researcher:</strong> Hunter Hustus<br>
            <strong>Title of Project:</strong> Nuclear Arsenals at Low Numbers: When Less is Different</p>
            <h3>Request to Participate in Research</h3>

            <p>Thank you for your interest in my research. We would like to invite you to participate in a session designed analyze nuclear force structures at various arsenal sizes. The session includes online responses to survey questions and use of a computer tool. The survey questions should take about 15 minutes to complete and the analysis of nuclear arsenals using the computer tool should take about 50 minutes. The complete session should take about 90 minutes.</p>

            <p>I hope you're participating in this this study because you are interested in nuclear weapons policy. Your participation could improve our understanding of how we can maintain strategic deterrence in differing future conditions. <strong>You must be at least 18 years old to participate.</strong></p>
            <p><strong>The decision to participate in this research project is voluntary.</strong> You do not have to participate and you can refuse to answer any question. Even if you begin the web-based online survey, you can stop at any time.</p>
            <p><strong>There are no foreseeable risks or discomforts to you for taking part in this study.</strong></p>

            <p><strong>There are no direct benefits to you from participating in this study.</strong> However, your responses may help us learn more about nuclear weapons force structures at small arsenal sizes.</p>

            <p>You will not be paid for your participation in this study.</p>

            <p><strong>Your part in this study will be kept confidential. However, because of the nature of web-based activity, it is possible that respondents could be identified by the IP address or other electronic record associated with the response. Neither the researcher nor anyone involved with this survey will be capturing those data. Any reports or publications based on this research will use only group data and will not identify you or any individual as being affiliated with this project.</strong></p>

            <p><strong>If you have any questions regarding electronic privacy,</strong> please feel free to contact Mark Nardone, NU's Director of Information Security via phone at 617-373-7901, or via email at <a href="mailto:privacy@neu.edu">privacy@neu.edu</a></p>

            <p><strong>If you have any questions about this study,</strong> please feel free to contact Hunter Hustus at 202-701-3318 or <a href="mailto:Hustus.h@husky.neu.edu">Hustus.h@husky.neu.edu</a>, the person mainly responsible for the research. You can also contact Dr Casper Harteveld at 617-373-4027 or at <a href="mailto:c.harteveld@neu.edu">c.harteveld@neu.edu</a>, the Principal Investigator.</p>

            <p><strong>If you have any questions regarding your rights as a research participant,</strong> please contact Nan C. Regina, Director, Human Subject Research Protection, 960 Renaissance Park, Northeastern University, Boston, MA 02115. Tel: 617-373-4588, Email: <a href="mailto:n.regina@neu.edu">n.regina@neu.edu</a>. You may call anonymously if you wish.</p>
            <p><strong>This study has been reviewed and approved by the Northeastern University Institutional Review Board (# CPS 15-2-01).</strong></p>
            <%= image_tag("approved_stamp.jpg", :alt => "Approved", class: "pull-right") %>
            <p><strong>By clicking on the I agree button below you are indicating that you consent to participate in this study.</strong> Please save or print a copy of this consent form for your records.</p>
            <p>Thank you for your time,<br>
            Hunter Hustus</p>

            
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <%= link_to "Acknowledge", new_initial_survey_path, :class => "btn btn-primary" %>
          </div>
        </div>
      </div>
    </div>
  </div><!--/.column-->
</div><!--/.row-->
</div>

app/views/static_pages/thank_you.html.erb
<div class="row">
  <div class="col-sm-12 col-md-6 col-md-push-3">
    <h1>Thank you!</h1>
    <p>Please contact <a href="mailto:hustus.h@husky.neu.edu">Hunter Hustus</a> if you have any questions or comments.</p>
  </div>
</div>