config/routes.rb
Rails.application.routes.draw do
  resources :follow_up_surveys

  resources :initial_surveys

  get 'static_pages/home'
  get 'static_pages/admin', :path => "admin"
  get 'static_pages/thank_you', :path => "thank_you"
  
  root 'static_pages#home'

  resources :simulations do
    get 'add_comments'
  end

end

app/models/follow_up_survey.rb
class FollowUpSurvey < ActiveRecord::Base
  serialize :groupOneSuggestions, Array
  serialize :groupTwoSuggestions, Array
  serialize :groupThreeSuggestions, Array
  serialize :groupFourSuggestions, Array
  serialize :groupFiveSuggestions, Array

  def self.to_csv(surveys)
    CSV.generate do |csv|
      csv << column_names
      surveys.each do |survey|
        csv << survey.attributes.values
      end
    end
  end

end

app/controllers/follow_up_surveys_controller.rb
class FollowUpSurveysController < ApplicationController
  before_action :set_follow_up_survey, only: [:show, :edit, :update, :destroy]

  # GET /follow_up_surveys
  # GET /follow_up_surveys.json
  def index
    @follow_up_surveys = FollowUpSurvey.all
    respond_to do |format|
      format.html { render :action => "index" }
      format.csv { send_data FollowUpSurvey.to_csv(@follow_up_surveys) }
    end
  end

  # GET /follow_up_surveys/1
  # GET /follow_up_surveys/1.json
  def show
  end

  # GET /follow_up_surveys/new
  def new
    @follow_up_survey = FollowUpSurvey.new
  end

  # GET /follow_up_surveys/1/edit
  def edit
  end

  # POST /follow_up_surveys
  # POST /follow_up_surveys.json
  def create
    @follow_up_survey = FollowUpSurvey.new(follow_up_survey_params)
    @follow_up_survey.user = cookies[:user] 

    respond_to do |format|
      if @follow_up_survey.save
        format.html { redirect_to static_pages_thank_you_path, notice: 'Follow up survey was successfully created.' }
        format.json { render :show, status: :created, location: @follow_up_survey }
      else
        format.html { render :new }
        format.json { render json: @follow_up_survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /follow_up_surveys/1
  # PATCH/PUT /follow_up_surveys/1.json
  def update
    respond_to do |format|
      if @follow_up_survey.update(follow_up_survey_params)
        format.html { redirect_to @follow_up_survey, notice: 'Follow up survey was successfully updated.' }
        format.json { render :show, status: :ok, location: @follow_up_survey }
      else
        format.html { render :edit }
        format.json { render json: @follow_up_survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /follow_up_surveys/1
  # DELETE /follow_up_surveys/1.json
  def destroy
    @follow_up_survey.destroy
    respond_to do |format|
      format.html { redirect_to follow_up_surveys_url, notice: 'Follow up survey was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_follow_up_survey
      @follow_up_survey = FollowUpSurvey.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def follow_up_survey_params
      params.require(:follow_up_survey).permit(
        :weaponsBenefit,
        :superiorRussia,
        :equalRussia,
        :adversaryRelevancy,
        :ssbnSurvivability,
        :survivabilityImportance,
        :ssbnValue,
        :icbmValue,
        :comments, 
        :groupOneSuggestions => [], 
        :groupTwoSuggestions => [],
        :groupThreeSuggestions => [], 
        :groupFourSuggestions => [], 
        :groupFiveSuggestions => []
        )
    end
end

app/helpers/follow_up_surveys_helper.rb
module FollowUpSurveysHelper
end

app/views/follow_up_surveys/_form.html.erb
<%= form_for(@follow_up_survey) do |f| %>
  <% if @follow_up_survey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@follow_up_survey.errors.count, "error") %> prohibited this follow_up_survey from being saved:</h2>

      <ul>
      <% @follow_up_survey.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="row">
  <div class="form-group col-sm-12">
    <%= f.label :weaponsBenefit, "1. There is a number of nuclear weapons <strong><em>sufficient</strong></em> to deter adversaries, <strong><em>regardless of the number of nuclear weapons they possess</strong></em>. Beyond that number, additional weapons provide little or no additional benefit.".html_safe, :class => "control-label" %>
    <div class="row">
      <div class="col-sm-12">
        <%= f.radio_button :weaponsBenefit, "1" %> Strongly disagree
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :weaponsBenefit, "2" %> Disagree
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :weaponsBenefit, "3" %> Neither agree nor disagree
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :weaponsBenefit, "4" %> Agree
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :weaponsBenefit, "5" %> Strongly agree
      </div>
    </div>
  </div>
  <div class="form-group col-sm-12">
    <%= f.label :superiorRussia, "2. To maintain strategic stability, the U.S. nuclear arsenal <strong><em>does not have to be superior</strong></em> in number to Russia’s nuclear arsenal.".html_safe, :class => "control-label" %>
    <div class="row">
      <div class="col-sm-12">
        <%= f.radio_button :superiorRussia, "1" %> Strongly disagree
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :superiorRussia, "2" %> Disagree
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :superiorRussia, "3" %> 
        Neither agree nor disagree
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :superiorRussia, "4" %> Agree
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :superiorRussia, "5" %> Strongly agree
      </div>
    </div>
  </div>
  <div class="form-group col-sm-12">
    <%= f.label :equalRussia, "3. To maintain strategic stability, the U.S. nuclear arsenal <strong><em>does not have to be at least equal</strong></em> in number to Russia’s nuclear arsenal.".html_safe %>
    <div class="row">
      <div class="col-sm-12">
        <%= f.radio_button :equalRussia, "1" %> Strongly disagree
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :equalRussia, "2" %> Disagree
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :equalRussia, "3" %> Neither agree nor disagree
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :equalRussia, "4" %> Agree
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :equalRussia, "5" %> Strongly agree
      </div>
    </div>
  </div>
  <div class="form-group col-sm-12">
    <%= f.label :adversaryRelevancy, "4. The number of nuclear weapons possessed by a potential adversary <strong><em>is irrelevant</em></strong> to determining the appropriate size of the U.S. nuclear arsenal.".html_safe, :class => "control-label" %>
    <div class="row">
      <div class="col-sm-12">
        <%= f.radio_button :adversaryRelevancy, "1" %> Strongly disagree
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :adversaryRelevancy, "2" %> Disagree
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :adversaryRelevancy, "3" %> Neither agree nor disagree
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :adversaryRelevancy, "4" %> Agree
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :adversaryRelevancy, "5" %> Strongly agree
      </div>
    </div>
  </div>
  <div class="form-group col-sm-12">
    <%= f.label :ssbnSurvivability, "5. The submarine-launched ballistic missile fleet (SSBN) is the <strong><em>most survivable</em></strong> of U.S. nuclear forces.".html_safe, :class => "control-label" %>
    <div class="row">
      <div class="col-sm-12">
        <%= f.radio_button :ssbnSurvivability, "1" %> Strongly disagree
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :ssbnSurvivability, "2" %> Disagree
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :ssbnSurvivability, "3" %> Neither agree nor disagree
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :ssbnSurvivability, "4" %> Agree
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :ssbnSurvivability, "5" %> Strongly agree
      </div>
    </div>
  </div>
  <div class="form-group col-sm-12">
    <%= f.label :survivabilityImportance, "6. Survivability is the <strong><em>most important attribute</em></strong> for a nuclear weapons system.".html_safe %>
    <div class="row">
      <div class="col-sm-12">
        <%= f.radio_button :survivabilityImportance, "1" %> Strongly disagree
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :survivabilityImportance, "2" %> Disagree
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :survivabilityImportance, "3" %> Neither agree nor disagree
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :survivabilityImportance, "4" %> Agree
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :survivabilityImportance, "5" %> Strongly agree
      </div>
    </div>
  </div>
  <div class="form-group col-sm-12">
    <%= f.label :ssbnValue, "7. The submarine-launched ballistic missile fleet (SSBN) is the <strong><em>most valuable</em></strong> component of U.S. nuclear forces.".html_safe, :class => "control-label" %>
    <div class="row">
      <div class="col-sm-12">
        <%= f.radio_button :ssbnValue, "1" %> Strongly disagree
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :ssbnValue, "2" %> Disagree
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :ssbnValue, "3" %> Neither agree nor disagree
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :ssbnValue, "4" %> Agree
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :ssbnValue, "5" %> Strongly agree
      </div>
    </div>
  </div>
  <div class="form-group col-sm-12">
    <%= f.label :icbmValue, "8. The value of the land-based intercontinental ballistic missile (ICBM) force <strong><em>diminishes as arsenal size decreases</em></strong>.".html_safe, :class => "control-label" %>
    <div class="row">
      <div class="col-sm-12">
        <%= f.radio_button :icbmValue, "1" %> Strongly disagree
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :icbmValue, "2" %> Disagree
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :icbmValue, "3" %> Neither agree nor disagree
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :icbmValue, "4" %> Agree
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :icbmValue, "5" %> Strongly agree
      </div>
    </div>
  </div>
  <div class="form-group col-sm-12">
    <p>9. In the five nuclear arsenals below, U.S. nuclear arsenal strategy should...</p>
    <%= render "/shared/survey_final", :f => f %>
  </div>
  <div class="form-group col-sm-12">
    <%= f.label :comments, "Please enter final comments.", :class => "user-label" %>
    <%= f.text_area :comments, :class => "form-control", :required => "true" %>
  </div>
  <div class="actions">
    <%= f.submit "Submit", :class => "btn btn-primary" %>
  </div>
</div>
<% end %>

app/views/follow_up_surveys/edit.html.erb
<h1>Editing follow_up_survey</h1>

<%= render 'form' %>

<%= link_to 'Show', @follow_up_survey %> |
<%= link_to 'Back', follow_up_surveys_path %>

app/views/follow_up_surveys/index.html.erb
<h1>Listing follow_up_surveys</h1>

<table>
  <thead>
    <tr>
      <th>Weaponsbenefit</th>
      <th>Superiorrussia</th>
      <th>Equalrussia</th>
      <th>Adversaryrelevancy</th>
      <th>Ssbnsurvivability</th>
      <th>Survivabilityimportance</th>
      <th>Ssbnvalue</th>
      <th>Icbmvalue</th>
      <th>Grouponesuggestions</th>
      <th>Grouptwosuggestions</th>
      <th>Groupthreesuggestions</th>
      <th>Groupfoursuggestions</th>
      <th>Groupfivesuggestions</th>
      <th>User</th>
      <th>Comments</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @follow_up_surveys.each do |follow_up_survey| %>
      <tr>
        <td><%= follow_up_survey.weaponsBenefit %></td>
        <td><%= follow_up_survey.superiorRussia %></td>
        <td><%= follow_up_survey.equalRussia %></td>
        <td><%= follow_up_survey.adversaryRelevancy %></td>
        <td><%= follow_up_survey.ssbnSurvivability %></td>
        <td><%= follow_up_survey.survivabilityImportance %></td>
        <td><%= follow_up_survey.ssbnValue %></td>
        <td><%= follow_up_survey.icbmValue %></td>
        <td><%= follow_up_survey.groupOneSuggestions %></td>
        <td><%= follow_up_survey.groupTwoSuggestions %></td>
        <td><%= follow_up_survey.groupThreeSuggestions %></td>
        <td><%= follow_up_survey.groupFourSuggestions %></td>
        <td><%= follow_up_survey.groupFiveSuggestions %></td>
        <td><%= follow_up_survey.user %></td>
        <td><%= follow_up_survey.comments %></td>
        <td><%= link_to 'Show', follow_up_survey %></td>
        <td><%= link_to 'Edit', edit_follow_up_survey_path(follow_up_survey) %></td>
        <td><%= link_to 'Destroy', follow_up_survey, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Follow up survey', new_follow_up_survey_path %>

app/views/follow_up_surveys/new.html.erb
<header>
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <h1><i class="fa fa-bomb"></i>Follow-up Survey</h1>
      </div>
    </div>
  </div>
</header>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-9">
      <%= render 'form' %>
    </div>
  </div>
</div>
<%= javascript_include_tag("survey_validation") %>

app/views/follow_up_surveys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Weaponsbenefit:</strong>
  <%= @follow_up_survey.weaponsBenefit %>
</p>

<p>
  <strong>Superiorrussia:</strong>
  <%= @follow_up_survey.superiorRussia %>
</p>

<p>
  <strong>Equalrussia:</strong>
  <%= @follow_up_survey.equalRussia %>
</p>

<p>
  <strong>Adversaryrelevancy:</strong>
  <%= @follow_up_survey.adversaryRelevancy %>
</p>

<p>
  <strong>Ssbnsurvivability:</strong>
  <%= @follow_up_survey.ssbnSurvivability %>
</p>

<p>
  <strong>Survivabilityimportance:</strong>
  <%= @follow_up_survey.survivabilityImportance %>
</p>

<p>
  <strong>Ssbnvalue:</strong>
  <%= @follow_up_survey.ssbnValue %>
</p>

<p>
  <strong>Icbmvalue:</strong>
  <%= @follow_up_survey.icbmValue %>
</p>

<p>
  <strong>Grouponesuggestions:</strong>
  <%= @follow_up_survey.groupOneSuggestions %>
</p>

<p>
  <strong>Grouptwosuggestions:</strong>
  <%= @follow_up_survey.groupTwoSuggestions %>
</p>

<p>
  <strong>Groupthreesuggestions:</strong>
  <%= @follow_up_survey.groupThreeSuggestions %>
</p>

<p>
  <strong>Groupfoursuggestions:</strong>
  <%= @follow_up_survey.groupFourSuggestions %>
</p>

<p>
  <strong>Groupfivesuggestions:</strong>
  <%= @follow_up_survey.groupFiveSuggestions %>
</p>

<%= link_to 'Edit', edit_follow_up_survey_path(@follow_up_survey) %> |
<%= link_to 'Back', follow_up_surveys_path %>