config/routes.rb
Rails.application.routes.draw do
  resources :follow_up_surveys

  resources :initial_surveys

  get 'static_pages/home'
  get 'static_pages/admin', :path => "admin"
  get 'static_pages/thank_you', :path => "thank_you"
  
  root 'static_pages#home'

  resources :simulations do
    get 'add_comments'
  end

end

app/models/initial_survey.rb
class InitialSurvey < ActiveRecord::Base
  serialize :groupOneSuggestions, Array
  serialize :groupTwoSuggestions, Array
  serialize :groupThreeSuggestions, Array
  serialize :groupFourSuggestions, Array
  serialize :groupFiveSuggestions, Array

  def self.to_csv(surveys)
    CSV.generate do |csv|
      csv << column_names
      surveys.each do |survey|
        csv << survey.attributes.values
      end
    end
  end

end

app/controllers/initial_surveys_controller.rb
class InitialSurveysController < ApplicationController
  before_action :set_initial_survey, only: [:show, :edit, :update, :destroy]

  # GET /initial_surveys
  # GET /initial_surveys.json
  def index
    @initial_surveys = InitialSurvey.all
    respond_to do |format|
      format.html { render :action => "index" }
      format.csv { send_data InitialSurvey.to_csv(@initial_surveys) }
    end
  end

  # GET /initial_surveys/1
  # GET /initial_surveys/1.json
  def show
  end

  # GET /initial_surveys/new
  def new
    @initial_survey = InitialSurvey.new
  end

  # GET /initial_surveys/1/edit
  def edit
  end

  # POST /initial_surveys
  # POST /initial_surveys.json
  def create
    @initial_survey = InitialSurvey.new(initial_survey_params)
    cookies[:user] = @initial_survey.user

    respond_to do |format|
      if @initial_survey.save
        format.html { redirect_to new_simulation_path, notice: 'Initial survey was successfully created.' }
        format.json { render :show, status: :created, location: @initial_survey }
      else
        format.html { render :new }
        format.json { render json: @initial_survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /initial_surveys/1
  # PATCH/PUT /initial_surveys/1.json
  def update
    respond_to do |format|
      if @initial_survey.update(initial_survey_params)
        format.html { redirect_to @initial_survey, notice: 'Initial survey was successfully updated.' }
        format.json { render :show, status: :ok, location: @initial_survey }
      else
        format.html { render :edit }
        format.json { render json: @initial_survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /initial_surveys/1
  # DELETE /initial_surveys/1.json
  def destroy
    @initial_survey.destroy
    respond_to do |format|
      format.html { redirect_to initial_surveys_url, notice: 'Initial survey was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_initial_survey
      @initial_survey = InitialSurvey.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def initial_survey_params
      params.require(:initial_survey).permit(
        :timeSpent, 
        :currentPosition, 
        :positionAffiliation, 
        :weaponsBenefit, 
        :superiorToRussia, 
        :equalToRussia, 
        :numberOfWeapons, 
        :ssbnSurvivability, 
        :survivabilityImportance, 
        :ssbnValuable, 
        :icbmValuable, 
        :user,
        :age,
        :groupOneSuggestions => [], 
        :groupTwoSuggestions => [],
        :groupThreeSuggestions => [], 
        :groupFourSuggestions => [], 
        :groupFiveSuggestions => []
      )
    end
end

app/helpers/initial_surveys_helper.rb
module InitialSurveysHelper
end

app/views/initial_surveys/_form.html.erb
<%= form_for(@initial_survey) do |f| %>
  <% if @initial_survey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@initial_survey.errors.count, "error") %> prohibited this initial_survey from being saved:</h2>

      <ul>
      <% @initial_survey.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="form-group col-sm-12">
      <%= f.label :user, "First, enter a username (required).", :class => "control-label user-label" %>
      <%= f.text_field :user, :class => "form-control", :required => true %>
    </div>
    <div class="form-group col-sm-12">
      <%= f.label :age, "1. What is your age?", :class => "control-label" %>
      <div class="row">
        <div class="col-sm-12">
          <%= f.radio_button :age, "18 to 24 years" %>
          <%= f.label :age, "18 to 24 years", :value => "18 to 24 years" %>
        </div>
        <div class="col-sm-12">
          <%= f.radio_button :age, "25 to 34 years" %>
          <%= f.label :age, "25 to 34 years", :value => "25 to 34 years" %>
        </div>
        <div class="col-sm-12">
          <%= f.radio_button :age, "35 to 44 years" %>
          <%= f.label :age, "35 to 44 years", :value => "35 to 44 years" %>
        </div>
        <div class="col-sm-12">
          <%= f.radio_button :age, "45 to 54 years" %>
          <%= f.label :age, "45 to 54 years", :value => "45 to 54 years" %>
        </div>
        <div class="col-sm-12">
          <%= f.radio_button :age, "55 to 64 years" %>
          <%= f.label :age, "55 to 64 years", :value => "55 to 64 years" %>
        </div>
        <div class="col-sm-12">
          <%= f.radio_button :age, "65 or older" %>
          <%= f.label :age, "65 or older", :value => "65 or older" %>
        </div>
      </div>
    </div>
    <div class="form-group col-sm-12">
      <%= f.label :timeSpent, "2. How often do you spend time on issues related to nuclear weapons?", :class => "control-label" %>
      <div class="row">
        <div class="col-sm-12 col-md-2">
          <%= f.radio_button :timeSpent, "Never" %>
          <%= f.label :timeSpent, "Never", :value => "never" %>
        </div>
        <div class="col-sm-12 col-md-2">
          <%= f.radio_button :timeSpent, "Monthly" %>
          <%= f.label :timeSpent, "Monthly", :value => "monthly" %>
        </div>
        <div class="col-sm-12 col-md-2">
          <%= f.radio_button :timeSpent, "Weekly" %>
          <%= f.label :timeSpent, "Weekly", :value => "weekly" %>
        </div>
        <div class="col-sm-12 col-md-2">
          <%= f.radio_button :timeSpent, "Daily" %>
          <%= f.label :timeSpent, "Daily", :value => "daily" %>
        </div>
      </div>
    </div>
  <div class="form-group col-sm-12">
    <%= f.label :currentPosition, "3. Which of the following best describes your current position or employment?", :class => "control-label" %>
    <div class="row">
      <div class="col-sm-12">
        <%= f.radio_button :currentPosition, "Federal Government" %> Federal Government
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :currentPosition, "Contractor" %> Contractor
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :currentPosition, "Think Tank" %> Think Tank
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :currentPosition, "Student" %> Student
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :currentPosition, "University" %> University
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :currentPosition, "Non-Governmental or International Organization" %> Non-Governmental or Internal Organization
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :currentPosition, "Other" %> Other
      </div>
    </div>
  </div>
  <div class="form-group col-sm-12">
    <%= f.label :positionAffiliation, "4. Which of the following best describes the national or international affiliation of your position or employment?", :class => "control-label" %>
    <div class="row">
      <div class="col-sm-12">
        <%= f.radio_button :positionAffiliation, "United States" %> United States
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :positionAffiliation, "NATO - other than the United States" %> NATO - other than the United States
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :positionAffiliation, "ASEAN - other than the United STates" %> ASEAN - other than the United States
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :positionAffiliation, "OAS - other than the United States" %> OAS - other than the United States
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :positionAffiliation, "Other" %> Other
      </div>
    </div>
  </div>
  <div class="form-group col-sm-12">
    <%= f.label :weaponsBenefit, "5. There is a number of nuclear weapons <strong><em>sufficient</strong></em> to deter adversaries, <strong><em>regardless of the number of nuclear weapons they possess</strong></em>. Beyond that number, additional weapons provide little or no additional benefit.".html_safe, :class => "control-label" %>
    <div class="row">
      <div class="col-sm-12">
        <%= f.radio_button :weaponsBenefit, "1" %> Strongly Disagree
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :weaponsBenefit, "2" %> Disagree
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :weaponsBenefit, "3" %> Neither agree nor disagree
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :weaponsBenefit, "4" %> Agree
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :weaponsBenefit, "5" %> Strongly agree
      </div>
    </div>
  </div>
  <div class="form-group col-sm-12">
    <%= f.label :superiorToRussia, "6. To maintain strategic stability, the U.S. nuclear arsenal <strong><em>does not have to be superior</strong></em> in number to Russia’s nuclear arsenal.".html_safe %>
    <div class="row">
      <div class="col-sm-12">
        <%= f.radio_button :superiorToRussia, "1" %> Strongly disagree
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :superiorToRussia, "2" %> Disagree
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :superiorToRussia, "3" %> Neither agree nor disagree
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :superiorToRussia, "4" %> Agree
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :superiorToRussia, "5" %> Strongly agree
      </div>
    </div>
  </div>
  <div class="form-group col-sm-12">
    <%= f.label :equalToRussia, "7. To maintain strategic stability, the U.S. nuclear arsenal <strong><em>does not have to be at least equal</strong></em> in number to Russia’s nuclear arsenal.".html_safe %>
    <div class="row">
      <div class="col-sm-12">
        <%= f.radio_button :equalToRussia, "1" %> Strongly disagree
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :equalToRussia, "2" %> Disagree
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :equalToRussia, "3" %> Neither agree nor disagree
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :equalToRussia, "4" %> Agree
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :equalToRussia, "5" %> Strongly agree
      </div>
    </div>
  </div>
  <div class="form-group col-sm-12">
    <%= f.label :numberOfWeapons, "8. The number of nuclear weapons possessed by a potential adversary <strong><em>is irrelevant</em></strong> to determining the appropriate size of the U.S. nuclear arsenal.".html_safe %>
    <div class="row">
      <div class="col-sm-12">
        <%= f.radio_button :numberOfWeapons, "1" %> Strongly disagree
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :numberOfWeapons, "2" %> Disagree
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :numberOfWeapons, "3" %> Neither agree nor disagree
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :numberOfWeapons, "4" %> Agree
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :numberOfWeapons, "5" %> Strongly agree
      </div>
    </div>
  </div>
  <div class="form-group col-sm-12">
    <%= f.label :ssbnSurvivability, "9. The submarine-launched ballistic missile fleet (SSBN) is the <strong><em>most survivable</em></strong> of U.S. nuclear forces.".html_safe, :class => "control-label" %>
    <div class="row">
      <div class="col-sm-12">
        <%= f.radio_button :ssbnSurvivability, "1" %> Strongly disagree
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :ssbnSurvivability, "2" %> Disagree
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :ssbnSurvivability, "3" %> Neither agree nor disagree
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :ssbnSurvivability, "4" %> Agree
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :ssbnSurvivability, "5" %> Strongly agree
      </div>
    </div>
  </div>
  <div class="form-group col-sm-12">
    <%= f.label :survivabilityImportance, "10. Survivability is the <strong><em>most important attribute</em></strong> for a nuclear weapons system.".html_safe %>
    <div class="row">
      <div class="col-sm-12">
        <%= f.radio_button :survivabilityImportance, "1" %> Strongly disagree
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :survivabilityImportance, "2" %> Disagree
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :survivabilityImportance, "3" %> Neither agree nor disagree
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :survivabilityImportance, "4" %> Agree
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :survivabilityImportance, "5" %> Strongly agree
      </div>
    </div>
  </div>
  <div class="form-group col-sm-12">
    <%= f.label :ssbnValuable, "11. The submarine-launched ballistic missile fleet (SSBN) is the <strong><em>most valuable</em></strong> component of U.S. nuclear forces.".html_safe %>
    <div class="row">
      <div class="col-sm-12">
        <%= f.radio_button :ssbnValuable, "1" %> Strongly disagree
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :ssbnValuable, "2" %> Disagree
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :ssbnValuable, "3" %> Neither agree nor disagree
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :ssbnValuable, "4" %> Agree
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :ssbnValuable, "5" %> Strongly agree
      </div>
    </div>
  </div>
  <div class="form-group col-sm-12">
    <%= f.label :icbmValuable, "12. The value of the land-based intercontinental ballistic missile (ICBM) force <strong><em>diminishes as arsenal size decreases</em></strong>.".html_safe %>
    <div class="row">
      <div class="col-sm-12">
        <%= f.radio_button :icbmValuable, "1" %> Strongly disagree
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :icbmValuable, "2" %> Disagree
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :icbmValuable, "3" %> Neither agree nor disagree
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :icbmValuable, "4" %> Agree
      </div>
      <div class="col-sm-12">
        <%= f.radio_button :icbmValuable, "5" %> Strongly agree
      </div>
    </div>
  </div>
  <div class="form-group col-sm-12">
    <p>13. In the five nuclear arsenals below, U.S. nuclear arsenal strategy should...</p>
    <%= render "/shared/survey_final", :f => f %>
    </div>
  </div>
  <div class="actions">
    <%= f.submit "Submit", :class => "btn btn-primary" %>
  </div>
</div>
<% end %>

app/views/initial_surveys/edit.html.erb
<h1>Editing initial_survey</h1>

<%= render 'form' %>

<%= link_to 'Show', @initial_survey %> |
<%= link_to 'Back', initial_surveys_path %>

app/views/initial_surveys/index.html.erb
<h1>Listing initial_surveys</h1>

<table>
  <thead>
    <tr>
      <th>Timespent</th>
      <th>Currentposition</th>
      <th>Positionaffiliation</th>
      <th>Weaponsbenefit</th>
      <th>Superiortorussia</th>
      <th>Equaltorussia</th>
      <th>Numberofweapons</th>
      <th>Ssbnsurvivability</th>
      <th>Survivabilityimportance</th>
      <th>Ssbnvaluable</th>
      <th>Icbmvaluable</th>
      <th>Grouponesuggestions</th>
      <th>Grouptwosuggestions</th>
      <th>Groupthreesuggestions</th>
      <th>Groupfoursuggestions</th>
      <th>Groupfivesuggestions</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @initial_surveys.each do |initial_survey| %>
      <tr>
        <td><%= initial_survey.timeSpent %></td>
        <td><%= initial_survey.currentPosition %></td>
        <td><%= initial_survey.positionAffiliation %></td>
        <td><%= initial_survey.weaponsBenefit %></td>
        <td><%= initial_survey.superiorToRussia %></td>
        <td><%= initial_survey.equalToRussia %></td>
        <td><%= initial_survey.numberOfWeapons %></td>
        <td><%= initial_survey.ssbnSurvivability %></td>
        <td><%= initial_survey.survivabilityImportance %></td>
        <td><%= initial_survey.ssbnValuable %></td>
        <td><%= initial_survey.icbmValuable %></td>
        <td><%= initial_survey.groupOneSuggestions %></td>
        <td><%= initial_survey.groupTwoSuggestions %></td>
        <td><%= initial_survey.groupThreeSuggestions %></td>
        <td><%= initial_survey.groupFourSuggestions %></td>
        <td><%= initial_survey.groupFiveSuggestions %></td>
        <td><%= initial_survey.user %></td>
        <td><%= link_to 'Show', initial_survey %></td>
        <td><%= link_to 'Edit', edit_initial_survey_path(initial_survey) %></td>
        <td><%= link_to 'Destroy', initial_survey, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Initial survey', new_initial_survey_path %>

app/views/initial_surveys/new.html.erb
<header>
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <h1><i class="fa fa-bomb"></i>Survey</h1>
        <%#= link_to "Opt out", new_simulation_path, :class => "btn reverse-btn" %>
      </div>
    </div>
  </div>
</header>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-9">
      <%= render 'form' %>
    </div>
  </div>
</div>
<%= javascript_include_tag("survey_validation") %>

app/views/initial_surveys/show.html.erb
<p id="notice"><%= sanitize(notice) %></p>

<p>
  <strong>Timespent:</strong>
  <%= @initial_survey.timeSpent %>
</p>

<p>
  <strong>Currentposition:</strong>
  <%= @initial_survey.currentPosition %>
</p>

<p>
  <strong>Positionaffiliation:</strong>
  <%= @initial_survey.positionAffiliation %>
</p>

<p>
  <strong>Weaponsbenefit:</strong>
  <%= @initial_survey.weaponsBenefit %>
</p>

<p>
  <strong>Superiortorussia:</strong>
  <%= @initial_survey.superiorToRussia %>
</p>

<p>
  <strong>Equaltorussia:</strong>
  <%= @initial_survey.equalToRussia %>
</p>

<p>
  <strong>Numberofweapons:</strong>
  <%= @initial_survey.numberOfWeapons %>
</p>

<p>
  <strong>Ssbnsurvivability:</strong>
  <%= @initial_survey.ssbnSurvivability %>
</p>

<p>
  <strong>Survivabilityimportance:</strong>
  <%= @initial_survey.survivabilityImportance %>
</p>

<p>
  <strong>Ssbnvaluable:</strong>
  <%= @initial_survey.ssbnValuable %>
</p>

<p>
  <strong>Icbmvaluable:</strong>
  <%= @initial_survey.icbmValuable %>
</p>

<p>
  <strong>Grouponesuggestions:</strong>
  <%= @initial_survey.groupOneSuggestions %>
</p>

<p>
  <strong>Grouptwosuggestions:</strong>
  <%= @initial_survey.groupTwoSuggestions %>
</p>

<p>
  <strong>Groupthreesuggestions:</strong>
  <%= @initial_survey.groupThreeSuggestions %>
</p>

<p>
  <strong>Groupfoursuggestions:</strong>
  <%= @initial_survey.groupFourSuggestions %>
</p>

<p>
  <strong>Groupfivesuggestions:</strong>
  <%= @initial_survey.groupFiveSuggestions %>
</p>

<%= link_to 'Edit', edit_initial_survey_path(@initial_survey) %> |
<%= link_to 'Back', initial_surveys_path %>